@startuml
|Server|
start
:创建socket;
:创建Channel;
:socket绑定port;
:socket等待客户端连接;
#aaaaaa:block;
detach
|Client|
:创建socket;
:连接到服务端;
#aaaaaa:block;
detach
|Server|
:监听客户端连接;
detach
|Client|
:连接成功;
:创建Channel;
:分配buffer内存;
:向buffer写数据;
stop
@enduml
